version: 2
jobs:
        build:
                working_directory: ~/repo
                docker:
                        # specify the version you desire here
                        - image: circleci/android:api-26-alpha                   

                environment:
                        # Customize the JVM maximum heap limit
                        _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
                        # JVM_OPTS: -Xmx3200m
                        TERM: dumb

                steps:
                        # checkout onto repo
                        - checkout
                       
                        # Download and cache dependencies
                        - restore_cache:
                                keys:
                                        - app-{{ checksum "build.gradle" }}
                        # setup environment
                        - run:
                                name: Setup Environment
                                command: ./scripts/environmentSetup.sh

                        - run:
                                name: Download dependencies
                                command: ./gradlew androidDependencies
                        
                        - save_cache:
                                key: app-{{ checksum "build.gradle" }}-{{ .Branch }}
                                paths:
                                        - ~/.gradle
                                keys:
                                        - app-{{ checksum "build.gradle" }}

                        - persist_to_workspace:
                                root: .
                                paths: .

        test:
                working_directory: ~/repo
                docker:
                        - image: circleci/android:api-26-alpha
                steps:
                        - attach_workspace:
                                at: .
                        
                        - restore_cache:
                                key: app-{{ checksum "build.gradle" }}-{{ .Branch }}
                                keys:
                                        - app-{{ checksum "app/build.gradle" }}

                        - run:
                                name: "Run lint tests"
                                command: ./gradlew lint test
                        - run:
                                name: Run Tests
                                command: ./gradlew test --no-daemon --max-workers 2

#                       - run:
#                               name: Setup emulator
#                               command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
#
#                       - run:
#                               name: Launch emulator
#                               command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
#                               background: true
#
#                       - run:
#                               name: Run Emulator Tests
#                               command: ./gradlew :app:connectedAndroidTest
                               
                        - store_test_results:
                                path: ~/repo/app/build/test-results

                        - store_artifacts:
                                path: ~/repo/app/build/reports/tests/
                                destination: /pdfreader/reports/

                        - persist_to_workspace:
                                root: .
                                paths: .

        deploy:
                working_directory: ~/repo
                docker:
                        - image: circleci/android:api-26-alpha
                steps:
                        - attach_workspace:
                                at: .
                                
                        - restore_cache:
                                key: app-{{ checksum "build.gradle" }}-{{ .Branch }}
                                keys:
                                        - app-{{ checksum "app/build.gradle" }}
                        
                        - store_artifacts:
                                path: ~/repo/app/build/outputs/apk/
                                destination: /app/apks/
                        
                        - deploy:
                                name: Deploy to Play Store
                                command: ./gradlew :app:publishApkRelease

workflows:
        version: 2
        build-test-deploy-tag:
                jobs:
                        - build
                        - test:
                                requires:
                                        - build
                        - deploy:
                                requires:
                                        - test
                                filters:
                                        branches:
                                                only:
                                                        - develop
                                                ignore:
                                                        - /^staging-.*/
                                                        - master
                                                        - /^feature-.*/
                                                        - /^feature/.*/
                                                        - /^bugfix-.*/
                                                        - /^bugfix/.*/
                                                        - /^hotfix/.*/

#                        - createReleaseTags:
#                                requires:
#                                        - deployProd
#                                        - deployBeta
#                                        - deployAlpha

#                                filters:
#                                        branches:
#                                                only:
#                                                        - master
#                                                        - develop
#                                                        - staging
#                                                ignore:
#                                                        - /^feature-.*/
#                                                        - /^feature/.*/
#                                                        - /^bugfix-.*/
#                                                        - /^bugfix/.*/
#                                                        - /^hotfix/.*/
